// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvlKLyMVpkcb3JSSYKpoA9ZjywDIbkcc',
    appId: '1:218629044285:web:65eb96504f2654da45d254',
    messagingSenderId: '218629044285',
    projectId: 'chatapp-5202f',
    authDomain: 'chatapp-5202f.firebaseapp.com',
    storageBucket: 'chatapp-5202f.appspot.com',
    measurementId: 'G-4Z6D334QQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5cJOKTcD4AYw1X3WZFvUldn-8GSMceuo',
    appId: '1:218629044285:android:b443294508d833d845d254',
    messagingSenderId: '218629044285',
    projectId: 'chatapp-5202f',
    storageBucket: 'chatapp-5202f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXds57MrA6H3xWUE7Aca8RmhztKRo853I',
    appId: '1:218629044285:ios:2282e065be32e40545d254',
    messagingSenderId: '218629044285',
    projectId: 'chatapp-5202f',
    storageBucket: 'chatapp-5202f.appspot.com',
    iosClientId: '218629044285-237cb2o4g3g7vb0ueb9c03qe2pevhlom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXds57MrA6H3xWUE7Aca8RmhztKRo853I',
    appId: '1:218629044285:ios:2282e065be32e40545d254',
    messagingSenderId: '218629044285',
    projectId: 'chatapp-5202f',
    storageBucket: 'chatapp-5202f.appspot.com',
    iosClientId: '218629044285-237cb2o4g3g7vb0ueb9c03qe2pevhlom.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
